export const SET_TUMBLER = "SET_TUMBLER";

export const CART = "CART";

export const ADD_PRODUCTS_TO_STORE = "ADD_PRODUCTS_TO_STORE";

export const SELECTED_PRODUCT = "SELECTED_PRODUCT";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
